apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: import-tests-go-zrgqclgr-workflow-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/import-tests-go-zrgqclgr-workflow-gitops